Initial HostObj class
ece496-blockchain-capstone-team/ece496-blockchain-simulator pull request #10
Opened 2021-12-27 21:53 UTC by dkhl65

Closes #2 
Removed all temporary demo code from the Network page because of changes to the HostObj functions.
Removed brodcastTransaction and takeAction because I think that it should be up to the Network class (central authority for the simulation) to keep track of time and handle the propagation of information between hosts. The Actions class is used to keep a log of actions for each host.

2021-12-29 01:10 UTC, ChenyanWang commented on src/services/HostRole.ts
> +    let allowedTypes = ['general', 'leader', 'malicious'];
expose allowedTypes as a constant list attribute or enum of HostRole and/or add a getter fxn

2021-12-29 01:14 UTC, ChenyanWang commented on src/components/Host/Host.test.tsx
> +for (let i = 0; i < 1000; i++) {
Maybe have 1000 be a constant and also write a couple tests for RNG host# networks
ie. idx0 = Math.floor(Math.random()*(MAX_HOSTS-MIN_HOSTS+1)+MIN_HOSTS)

2021-12-29 01:15 UTC, ChenyanWang commented on src/components/Host/Host.test.tsx
> +  let removed01 = hosts[0].removeConnectedNode(hosts[1]);
Do we want a function to remove 2 ways, rather than calling it for both hosts?

2021-12-29 01:16 UTC, ChenyanWang requested changes
Overall looks pretty cleaned up!
Pretty glad you changed the "HostType" file to "HostRole", perhaps expose a global enum for all types of roles a host may take
Good job!

2021-12-29 21:02 UTC, dkhl65 commented on src/services/HostRole.ts
> +    let allowedTypes = ['general', 'leader', 'malicious'];
I added a getter function.

2021-12-29 21:03 UTC, dkhl65 commented on src/components/Host/Host.test.tsx
> +for (let i = 0; i < 1000; i++) {
I used a constant 1000, rather than random. Random values is not appropriate for a unit test since it should run the same way every time.

2021-12-29 21:09 UTC, dkhl65 commented on src/components/Host/Host.test.tsx
> +  let removed01 = hosts[0].removeConnectedNode(hosts[1]);
I made a function for removing both ways. Keep in mind that during simulation, this function is used only to change the info displayed for the Host view. To truly delete the connection, the NetworkObj class needs to delete its Connection object.

2021-12-29 23:28 UTC, ChenyanWang approved these changes
LGTM

2021-12-30 00:13 UTC, dkhl65 commented on src/services/HostRole.ts
> +    let allowedTypes = ['general', 'leader', 'malicious'];
Actually, based on your comment on Messenger, I decided to delete HostRole and replace it with a static enum inside Host so you can use Host.Role.General instead of 'general'.

2021-12-30 00:18 UTC, dkhl65 commented
I decided to delete the HostRole class and replace it with a static enum inside the Host class so you can use Host.Role.General instead of 'general'. Let me know if this is better. There is no allowedTypes function, but there is no need to input a string. The type of role is restricted by the enum.

2022-01-05 23:22 UTC, davidjyee approved these changes
Looks good to me

2022-01-05 23:28 UTC, ChenyanWang approved these changes
LGTM

2022-01-07 22:30 UTC, RafsanHaque approved these changes

2022-01-07 22:31 UTC, merged