Initial block and chain class
ece496-blockchain-capstone-team/ece496-blockchain-simulator pull request #14
Opened 2022-01-16 22:37 UTC by ChenyanWang

Closes #1 

Removed deprecated demo related functionality
Removed "updateChain" functionality, replaced it with "replaceChain"
Added new "chain" view tab and corresponding tests

2022-01-16 23:15 UTC, RafsanHaque approved these changes

2022-01-17 03:36 UTC, dkhl65 requested changes
Doc comments for class properties and static functions. The TODO for the Host class can be implemented now.

2022-01-17 03:36 UTC, dkhl65 commented on src/services/Block.ts
> +  private valid: boolean; // TODO: In host class, add validate() function to set validatorId and valid = true
You can go ahead and add that function to the Host class now. Also, it would be nice to also have doc comments for the class properties.

2022-01-17 03:36 UTC, dkhl65 commented on src/services/Block.ts
> +  static genesisBlock(): BlockObj {
Static functions should have doc comments also.

2022-01-17 03:38 UTC, ChenyanWang commented on src/services/Block.ts
> +  static genesisBlock(): BlockObj {
thanks for noticing, good catch, ill add in these updates later today or early tommorow

2022-01-17 03:38 UTC, ChenyanWang commented on src/services/Block.ts
> +  private valid: boolean; // TODO: In host class, add validate() function to set validatorId and valid = true
got it will add them

2022-01-18 03:04 UTC, dkhl65 approved these changes
Unit tests are passing, doc comments are okay, the project compiles.

2022-01-19 02:54 UTC, davidjyee approved these changes

2022-01-19 03:08 UTC, merged