Added network reducer and redux-react framework
ece496-blockchain-capstone-team/ece496-blockchain-simulator pull request #16
Opened 2022-01-25 01:39 UTC by davidjyee

Added basic redux-react network reducer, is viewable from browser extension (installation instructions have been added to read me). 

Will be adding initialization and working through implementation of Host on redux next to ensure compatibility, just wanted to merge current framework to dev so we are all working on the same framework together.

2022-01-25 02:33 UTC, dkhl65 requested changes
Make sure unit tests are passing before merge.

2022-01-25 02:33 UTC, dkhl65 commented on src/components/Home/Home.tsx
> +    </Grid>
Please update Home.test.tsx so it passes.

2022-01-25 03:26 UTC, davidjyee commented on src/components/Home/Home.tsx
> +    </Grid>
Fixed

2022-01-25 03:41 UTC, dkhl65 approved these changes

2022-01-25 06:23 UTC, ChenyanWang commented on src/components/Home/Home.test.tsx
>    render(<Home />);
Update test to check for "Home" header

2022-01-25 06:24 UTC, ChenyanWang commented on src/components/Network/Network.tsx
> +  // let network = new NetworkObj(5);
Remove unused comments

2022-01-25 06:25 UTC, ChenyanWang commented on src/reducers/network.ts
> +      // for (let nodeid = 0; nodeid < numNodes; nodeid++){
Please remove unused code

2022-01-25 06:26 UTC, ChenyanWang commented on src/reducers/network.ts
> +      // for (let nodeid = 0; nodeid < numNodes; nodeid++){
Move this to the network test

2022-01-25 06:46 UTC, ChenyanWang requested changes
Please fix the empty "home" page test

Will approve after, as we need react redux for other dev
Note: still need to fix porting of network class (as it is now empty) and remove unused code comments

2022-01-25 21:07 UTC, ChenyanWang approved these changes
LGTM!

2022-01-26 15:39 UTC, RafsanHaque approved these changes

2022-01-26 15:40 UTC, merged