Feature/network map
ece496-blockchain-capstone-team/ece496-blockchain-simulator pull request #20
Opened 2022-02-27 16:12 UTC by davidjyee

Finished basic network map, renders locations stored in the network slice

2022-02-27 17:13 UTC, dkhl65 commented
The pin icons locations are centered on the circle instead of the point at the bottom. Is there any way to change this?

2022-02-27 18:53 UTC, RafsanHaque approved these changes

2022-02-27 19:24 UTC, ChenyanWang commented on src/components/Network/Network.tsx
> +  latitude: 51.47,
Is there a reason for these choice of hard values?

2022-02-27 19:25 UTC, ChenyanWang commented on src/components/Network/Network.tsx
> +            mapboxApiAccessToken="pk.eyJ1IjoiZGF2aWR5ZWUiLCJhIjoiY2wwMzh3d202MGt6NjNpbWo4ZHRtbHlwZCJ9.L3KYonYcVS3OAIL_eueY3w"
Remove this from git :)
Please have it as an environment variable

2022-02-27 19:26 UTC, ChenyanWang commented on src/slices/network.ts
> +            latitude: 37.54560327062006,
Do we also want a map of locations to ids (ie. Toronto is 0, Tokyo is 1)?

2022-02-27 19:26 UTC, ChenyanWang requested changes
Please rebase from dev
(9 commits ahead, 1 behind dev)

Looks good, just had some questions re: hard values + api key

2022-02-27 19:33 UTC, dkhl65 reviewed
The pin icons locations are centered on the circle instead of the point at the bottom. Is there any way to change this?

2022-02-28 03:42 UTC, davidjyee commented on src/components/Network/Network.tsx
> +  latitude: 51.47,
For testing purposes currently

2022-02-28 03:45 UTC, davidjyee commented on src/components/Network/Network.tsx
> +            mapboxApiAccessToken="pk.eyJ1IjoiZGF2aWR5ZWUiLCJhIjoiY2wwMzh3d202MGt6NjNpbWo4ZHRtbHlwZCJ9.L3KYonYcVS3OAIL_eueY3w"
It is okay to have it imbedded in the application/public on git, it is designed to be a public key

2022-02-28 03:46 UTC, davidjyee commented on src/slices/network.ts
> +            latitude: 37.54560327062006,
I don't think it's a huge issue, I will be adding names so you can tooltip; id's ideally shouldn't need to be visible to client since they don't mean much to them

2022-02-28 03:54 UTC, davidjyee commented
> The pin icons locations are centered on the circle instead of the point at the bottom. Is there any way to change this?

Done

2022-02-28 04:11 UTC, dkhl65 reviewed
Thanks for fixing the map pins. Now I noticed that the stuff pages other than Network are too close to the top bar. Can you add top padding to all those pages (e.g. by editing global.css) without affecting the map?

2022-02-28 05:05 UTC, ChenyanWang approved these changes
Maybe add the host tests you removed to the network test file, otherwise LGTM

2022-02-28 05:25 UTC, davidjyee commented
> Thanks for fixing the map pins. Now I noticed that the stuff pages other than Network are too close to the top bar. Can you add top padding to all those pages (e.g. by editing global.css) without affecting the map?

Fixed, in future don't use a global.css for padding since it doesn't play nice with chakra. Just use a box with the appropriate padding for the page.

2022-02-28 06:06 UTC, dkhl65 approved these changes

2022-02-28 12:17 UTC, merged